### ISSUE TITLE
Makefile error: no rule to make 'libsm.a'

### ISSUE THREAD

**Issue by lukenels** [keystone-enclave/riscv-pk#18]
Hi! I'm trying to figure out how to build the security monitor. I've got the RISC-V toolchain installed on my Ubuntu machine and am running the build script as shown in the README on the `keystone` branch.

The build proceeds normally for a while, but eventually gets stuck trying to build 'libsm.a' for which there is no Makefile rule. I've posted the build script I'm using as well as some system information and commit hash I'm using.

```
> mkdir build; cd build; ../configure --prefix=/opt/riscv --host=riscv64-linux-gnu; make 
[... lots of output ...]
make: *** No rule to make target 'libsm.a', needed by 'pk'.  Stop.
```

```
> git rev-parse HEAD
416b89be4eec767c3f8f96d57f3c9ba12add70c8

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

> riscv64-linux-gnu-gcc --version
riscv64-linux-gnu-gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by dkohlbre** [comment]
Hi,
Our README for building a bbl image is out of date. Since we've only been building it as part of a full keystone build we hadn't noticed that. Sorry. I'll make sure the README gets updated.

In the meantime, try either:
Using the Makefile (or copying its flow) https://github.com/keystone-enclave/keystone/blob/master/Makefile#L38
Or the docs here: http://docs.keystone-enclave.org/en/dev/Getting-Started/Running-Keystone-with-QEMU.html#build-berkeley-bootloader-bbl-with-keystone-security-monitor

Let me know if you run into any issues with those!

**Comment by lukenels** [comment]
Awesome thanks! I missed the parent project and was just trying to build this on its own 🤦‍♂️
